spring:
  main:
    log-startup-info: false
    banner-mode: off
  h2:
    console.enabled: true
  sql:
    init:
      mode: always
  datasource:
    driverClassName: org.h2.Driver
    url: jdbc:h2:file:./db/filmorate
    username: sa
    password: password

logging.level:
  root: WARN