CREATE TABLE IF NOT EXISTS users (
    id       BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    email    VARCHAR(64) NOT NULL,
    login    VARCHAR(30) NOT NULL,
    name     VARCHAR(50),
    birthday DATE NOT NULL
);

create TABLE IF NOT EXISTS friends (
    id           BIGINT NOT NULL REFERENCES users (id) ON DELETE CASCADE,
    friend_id    BIGINT NOT NULL REFERENCES users (id) ON DELETE CASCADE,
    reciprocity  BOOLEAN NOT NULL DEFAULT TRUE,
    CONSTRAINT   friends PRIMARY KEY (id, friend_id)
);

create TABLE IF NOT EXISTS genre (
    id   INTEGER PRIMARY KEY,
    name VARCHAR(50) NOT NULL
);

create TABLE IF NOT EXISTS mpa (
    id   INTEGER PRIMARY KEY,
    name VARCHAR(5) NOT NULL
);

CREATE TABLE IF NOT EXISTS films (
    id           BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name         VARCHAR(100) NOT NULL,
    description  VARCHAR(200) NOT NULL,
    release_date DATE NOT NULL,
    duration     INTEGER NOT NULL,
    mpa_id       INTEGER NOT NULL REFERENCES mpa (id)
);

create TABLE IF NOT EXISTS genres (
    id         BIGINT NOT NULL REFERENCES films (id) ON DELETE CASCADE,
    genre_id  INTEGER NOT NULL REFERENCES genre (id) ON DELETE CASCADE,
    CONSTRAINT genres PRIMARY KEY (id, genre_id)
);

create TABLE IF NOT EXISTS likes (
    film_id  BIGINT NOT NULL REFERENCES films (id) ON DELETE CASCADE,
    user_id  BIGINT NOT NULL REFERENCES users (id) ON DELETE CASCADE,
    CONSTRAINT likes PRIMARY KEY (film_id, user_id)
);